import streamlit
streamlit.title('MY PARENTS NEW HEALTHY DINER')

STREAMLIT.HEADER('BREAKFAST MENU')
STREAMLIT.TEST('OMEGA 3 & BLUEBERRY OATMEAL')
STREAMLIT.TEXT('KALE, SPINACH & ROCKET SMOOTHIE')
STREAMLIT.TEXT('HARD-BOILED FREE-RANGE EGG')
